#!/usr/bin/env bash
set -e

if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

yes | pip2 install neovim
yes | pip3 install neovim
gem install neovim

mkdir -p ${HOME}/.config
ln -s ${HOME}/.vim ${HOME}/.config/nvim

vim -u ${HOME}/.dotfiles//topics/vim/plugins.vim +PlugClean! +PlugUpdate +qa!
