#!/usr/bin/env bash
set -e

if [ ! -f ~/.vim/autoload/plug.vim ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u ${HOME}/.dotfiles//topics/vim/plugins.vim +PlugClean! +PlugUpdate +qa!
