#!/bin/zsh
set -e

cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# load zshrc and check if antibody is working
source ~/.zshrc

test "$(antibody list | wc -l)" -gt 1 || {
  echo "expecting some bundles loaded" >&2
  exit 1
}

# check if a random plugin is working (meaning that the bundles were loaded)
show_colors
