session_name: dots
windows:
- window_name: dots
  start_directory: ${DOTFILES}/
  options:
    automatic-rename: 'off'
  panes:
    - shell_command: vim .
- window_name: private
  start_directory: ${PRIVATE_DOTFILES}/
  options:
    automatic-rename: 'off'
  panes:
    - shell_command: vim .
- window_name: scratch
  start_directory: ${DOTFILES}
  options:
    automatic-rename: 'off'
  panes:
    - pane
