language: python
os:
  - linux
  # - osx
before_install:
  - pip install vim-vint
  - make all
install:
  - ./install
  # - vim +PlugClean! +PlugUpdate +qa!
  - exec "$SHELL" -l
script:
  - show_colors
after_success:
  - ./uninstall
