#! /usr/bin/env bash

set -e

. ./support/functions

info "Bootstrapping Dotfiles..."
echo ''

if test "$(uname)" = "Darwin"; then

  if test ! "$(command -v gcc)"; then
    info "Installing XCode..."
    xcode-select --install
  fi

  info "Installing Homebrew..."
  if test ! "$(command -v brew)"; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" | while read -r line; do success "$line"; done
  else
    while read -r brw; do
      success "${brw}"
    done < <(brew update)
    echo ''
  fi

  info "Updating Brew Bundles..."
  while read -r bun; do
    success "${bun}"
  done < <(brew bundle)
  echo ''

  "$(brew --prefix)/opt/fzf/install --all"

fi
