#! /usr/bin/env bash

echo "This file should be sourced..."
echo ''

export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_RUNTIME_DIR=~/tmp/xdg_runtime

while read -r env; do
  echo "Sourcing $env"
  # shellcheck disable=SC1090
  source "${env}"
done < <(find . -name env.zsh)
echo ''

echo "Setting PATH..."
echo ''

source zsh/path.zsh

echo "Installing Git submodules..."
while read -r sm; do
  echo "${sm}"
done < <(git submodule update --init --recursive)
echo ''

echo "Installing Homebrew..."
if test ! "$(command -v brew)"; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  while read -r brw; do
    echo "${brw}"
  done < <(brew update)
  echo ''
fi

