################################################################################
# Taps
################################################################################

# tap 'snyk/tap'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'warrensbox/tap'

################################################################################
# Casks
################################################################################

cask '1password-cli'
cask 'alacritty'
cask 'alfred'
cask 'balenaetcher'
cask 'bartender'
cask 'better-window-manager'
cask 'bruno'
cask 'coconutbattery'
cask 'dropbox'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-meslo-for-powerline'
cask 'font-meslo-lg-nerd-font'
cask 'font-roboto-mono-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
cask 'gitx'
cask 'gpg-suite'
cask 'istat-menus'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'omnidisksweeper'
cask 'omnigraffle'
cask 'slack'
cask 'the-unarchiver'
cask 'utm'
cask 'vagrant'
cask 'visual-studio-code'
cask 'vlc'


################################################################################
# Simple brews
################################################################################

# # brew 'hub'
# # brew 'lua@5.1'
# # brew 'luarocks'
# brew 'sbt'
# brew 'snyk'
# brew 'sqlfluff'
# brew 'sqlite'
# brew 'terraform'
# brew 'tflint'
# brew 'tfsec'
brew 'ack'
brew 'age'
brew 'ansible'
brew 'ansible-lint'
brew 'antidote'
brew 'asdf'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'cmake'
brew 'colima'
brew 'coreutils'
brew 'cowsay'
brew 'direnv'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gawk'
brew 'gettext'
brew 'gh'
brew 'git'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'go-task'
brew 'golangci-lint'
brew 'gpg'
brew 'grep'
brew 'gzip'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'k3d'
brew 'kubectx'
brew 'less'
brew 'make'
brew 'markdownlint-cli'
brew 'mas'
brew 'maven'
brew 'ninja'
brew 'nmap'
brew 'node'
brew 'openssh'
brew 'openssl'
brew 'pandoc'
brew 'par'
brew 'pcre'
brew 'perl'
brew 'pinentry-mac'
brew 'pipx'
brew 'postgresql@15', restart_service: :changed
brew 'pre-commit'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rg'
brew 'rpm'
brew 'ruby'
brew 'screen'
brew 'screenresolution'
brew 'sops'
brew 'ssh-copy-id'
brew 'stern'
brew 'stow'
brew 'stylua'
brew 'telnet'
brew 'terraform-docs'
brew 'terragrunt'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'tree-sitter'
brew 'vault'
brew 'viddy'
brew 'virtualenv'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'yq'
brew 'zsh'


# ################################################################################
# # Mac App Store
mas 'Blackmagic Disk Speed Test (3.2)', id: 425264550
mas 'Dark Reader for Safari (1.4.2)', id: 1438243180
mas 'HP Smart for Desktop (5.6.1)', id: 1474276998
mas 'Marked 2 (2.5.31)', id: 890031187
