mas 'Deliveries: a package tracker', id: 924726344
mas 'Marked 2', id: 890031187
mas 'Microsoft Remote Desktop (8.0)', id: 715768417
mas 'Paprika Recipe Manager 3', id: 1303222628
mas 'Tweetbot for Twitter', id: 557168941
mas 'Xcode', id: 497799835
mas 'feedly. Read more, know more.', id: 865500966

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'getantibody/tap'
tap 'go-delve/delve'
tap 'homebrew/services'
tap 'universal-ctags/universal-ctags'

cask_args appdir: '/Applications'

cask 'caskroom/fonts/font-meslo-for-powerline'
cask 'caskroom/fonts/font-source-code-pro-for-powerline'
cask 'caskroom/fonts/font-roboto-mono-for-powerline'

# cask 'intellij-idea'
# cask 'jce-unlimited-strength-policy'
cask 'alfred'
cask 'atom'
cask 'bartender'
cask 'better-window-manager'
cask 'box-sync'
cask 'carbon-copy-cloner'
cask 'cleanmymac'
cask 'coconutbattery'
cask 'colloquy'
cask 'dbvisualizer'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2'
cask 'mactex'
cask 'macupdate-desktop'
cask 'microsoft-office'
cask 'minikube'
cask 'monolingual'
cask 'omnidisksweeper'
cask 'omnigraffle'
cask 'onyx'
cask 'postman'
cask 'rowanj-gitx'
cask 'slack'
cask 'spotify'
cask 'vagrant'
cask 'visual-studio-code'
cask 'vlc'
cask 'xquartz'

brew 'ack'
brew 'ansible'
brew 'antibody'
brew 'autoconf'
brew 'automake'
brew 'bash'
brew 'berkeley-db'
brew 'boost'
brew 'cmake'
brew 'coreutils'
brew 'exa'
brew 'findutils'
brew 'freetype'
brew 'fzf'
brew 'gawk', args: ["with-default-names"]
brew 'gdbm'
brew 'gettext'
brew 'git'
brew 'git-extras'
brew 'glib'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnutls'
brew 'go', args: ["cross-compile-common"]
brew 'go-delve/delve/delve'
brew 'googler'
brew 'grep'
brew 'gti'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'jmeter', args: ["with-plugins"]
brew 'jpeg'
brew 'jq'
brew 'kafka'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'libevent'
brew 'libffi'
brew 'libmagic'
brew 'libpng'
brew 'libtasn1'
brew 'libtiff'
brew 'libtool'
brew 'libyaml'
brew 'lua51'
brew 'mas'
brew 'neofetch'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'oniguruma'
brew 'openssl'
brew 'ossp-uuid'
brew 'pandoc'
brew 'par'
brew 'pcre'
brew 'perl'
brew 'pkg-config'
brew 'popt'
brew 'postgresql', restart_service: :changed
brew 'python'
brew 'ranger'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis', restart_service: :changed
brew 'rg'
brew 'rpm'
brew 'ruby'
brew 's-lang'
brew 'sbt'
brew 'screen'
brew 'screenresolution'
brew 'shellcheck'
brew 'sip'
brew 'source-highlight'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'stow'
brew 'tcptraceroute'
brew 'telnet'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'universal-ctags', args: ["HEAD"]
brew 'utf8proc'
brew 'vim'
brew 'wget'
brew 'xz'
brew 'zsh'
