################################################################################
# Taps
################################################################################

tap 'homebrew/cask-fonts'
tap 'homebrew/services'
# tap 'snyk/tap'
tap 'warrensbox/tap'

################################################################################
# Casks
################################################################################

cask '1password-cli'
cask 'alacritty'
cask 'alfred'
cask 'balenaetcher'
cask 'bartender'
# cask 'basictex'
cask 'better-window-manager'
cask 'coconutbattery'
cask 'dropbox'
# cask 'firefox'
cask 'font-meslo-for-powerline'
cask 'font-meslo-lg-nerd-font'
cask 'font-roboto-mono-nerd-font'
cask 'font-sauce-code-pro-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
# cask 'insomnia'
cask 'istat-menus'
cask 'jetbrains-toolbox'
cask 'karabiner-elements'
cask 'omnidisksweeper'
cask 'omnigraffle'
cask 'postman'
cask 'gitx'
cask 'slack'
cask 'the-unarchiver'
cask 'vagrant'
# cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'


################################################################################
# Simple brews
################################################################################

# # brew 'hub'
# # brew 'lua@5.1'
# # brew 'luarocks'
# # brew 'ranger'
# # brew 'rpm'
# brew 'antlr'
# brew 'berkeley-db'
# brew 'boost'
# brew 'cmatrix'
# brew 'dive'
# brew 'figlet'
# brew 'flake8'
# brew 'freetype'
# brew 'gdbm'
# brew 'git-extras'
# brew 'git-filter-repo'
# brew 'glib'
# brew 'graphviz'
# brew 'imagemagick'
# brew 'jpeg'
# brew 'kubeseal'
# brew 'libevent'
# brew 'libffi'
# brew 'libmagic'
# brew 'libpng'
# brew 'libtasn1'
# brew 'libtiff'
# brew 'libtool'
# brew 'libyaml'
# brew 'nats-server', restart_service: :changed
# brew 'ncdu'
# brew 'neofetch'
# brew 'oniguruma'
# brew 'ossp-uuid'
# brew 'pandoc'
# brew 'pkg-config'
# brew 'popt'
# brew 'postgis'
# brew 'prettier'
# brew 'proselint'
# brew 'pylint'
# brew 'readline'
# brew 'rmlint'
# brew 's-lang'
# brew 'shellcheck'
# brew 'shellharden'
# brew 'shfmt'
# brew 'sip'
# brew 'snyk'
# brew 'source-highlight'
# brew 'sqlfluff'
# brew 'sqlite'
# brew 'tcptraceroute'
# brew 'tflint'
# brew 'tfsec'
# brew 'tfswitch'
# brew 'tidy-html5'
# brew 'utf8proc'
# brew 'wdiff'
# brew 'weechat'
# brew 'xz'
brew 'ack'
brew 'age'
brew 'ansible'
brew 'ansible-lint'
brew 'antidote'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'cmake'
brew 'colima'
brew 'coreutils'
brew 'cowsay'
brew 'direnv'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'docker-credential-helper'
brew 'eza'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gawk'
brew 'gettext'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnutls'
brew 'go-task'
brew 'golangci-lint'
brew 'grep'
brew 'gzip'
brew 'htop'
brew 'httpie'
brew 'java'
brew 'jq'
brew 'k3d'
brew 'kubectx'
brew 'less'
brew 'make'
brew 'markdownlint-cli'
brew 'mas'
brew 'ninja'
brew 'nmap'
brew 'node'
brew 'openssh'
brew 'openssl'
brew 'par'
brew 'pcre'
brew 'perl'
brew 'pipx'
brew 'postgresql@15', restart_service: :changed
brew 'pre-commit'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'rg'
brew 'ruby'
brew 'screen'
brew 'screenresolution'
brew 'sops'
brew 'ssh-copy-id'
brew 'stern'
brew 'stow'
brew 'stylua'
brew 'telnet'
brew 'terraform'
brew 'terraform-docs'
brew 'terragrunt'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'tree-sitter'
brew 'vault'
brew 'viddy'
brew 'virtualenv'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'yq'
brew 'zsh'


# ################################################################################
# # Mac App Store
mas 'Blackmagic Disk Speed Test (3.2)', id: 425264550
mas 'Dark Reader for Safari (1.4.2)', id: 1438243180
mas 'HP Smart for Desktop (5.6.1)', id: 1474276998
mas 'Marked 2 (2.5.31)', id: 890031187
# # mas 'Microsoft Excel (16.22)', id: 462058435
# # mas 'Microsoft OneNote (16.22)', id: 784801555
# # mas 'Microsoft Outlook (16.22)', id: 985367838
# # mas 'Microsoft PowerPoint (16.22)', id: 462062816
# # mas 'Microsoft Remote Desktop (10.3.11)', id: 1295203466
# # mas 'Microsoft Word (16.22)', id: 462054704
# mas 'Numbers (6.1)', id: 409203825
# # mas 'OneDrive (19.002.0107)', id: 823766827
