#!/usr/bin/env bash
set -e

SUMKENO_URL="git@github.com:sumneko/lua-language-server.git"

if [ ! -d ${1} ]; then
  echo "${1} is not present, cloning..."
  git clone ${SUMKENO_URL} ${1}
fi

cd ${1}
git pull -f
git submodule update --init --recursive
cd 3rd/luamake
compile/install.sh
cd ../..
./3rd/luamake/luamake rebuild
