#!/usr/bin/env bash
set -e

if [ ! -f ~/.vim/autoload/plug.vim ]; then
  curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim >> /dev/null
fi

pip2 install -U -r requirements.txt
pip3 install -U -r requirements.txt

npm install -g \
  jsonlint \
  markdownlint-cli

gem install neovim

[ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
[ ! -L "${HOME}/.config/nvim" ] && ln -s "${HOME}/.vim" "${HOME}/.config/nvim"
