#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

yes | pip2 uninstall -r "${DIR}/requirements.txt"
yes | pip3 uninstall -r "${DIR}/requirements.txt"

npm uninstall -g \
  jsonlint \
  markdownlint-cli \
  alex \
  ember-template-lint

gem uninstall neovim

rm -rf "${HOME}/.vim"
rm -rf "${HOME}/.viminfo"
rm -rf "${HOME}/.vimrc_background"
rm -rf "${HOME}/.dotfiles/vim/vim.symlink/autoload/plug.vim"
rm -rf "${HOME}/.dotfiles/vim/vim.symlink/plugged"
rm -rf "${HOME}/.ideavimrc"
rm -rf "${HOME}/.config/nvim"

