#!/usr/bin/env bash
set -e

rm -rf ${HOME}/.vim
rm -rf ${HOME}/.viminfo
rm -rf ${HOME}/.vimrc_background
rm -rf ${HOME}/.dotfiles/vim/vim.symlink/autoload/plug.vim
rm -rf ${HOME}/.dotfiles/vim/vim.symlink/plugged
rm -rf ${HOME}/.ideavimrc

rm -rf ${HOME}/.config/nvim

yes | pip2 uninstall neovim
yes | pip3 uninstall neovim
gem uninstall neovim
