#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f "${HOME}.vim/autoload/plug.vim" ]; then
  curl -sfLo "${HOME}/.vim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim >> /dev/null
fi

yes | pip2 install -U -r "${DIR}/requirements.txt"
yes | pip3 install -U -r "${DIR}/requirements.txt"

npm install -g \
  jsonlint \
  markdownlint-cli \
  alex \
  ember-template-lint

gem install neovim

[ ! -d "${HOME}/.config" ] && mkdir -p "${HOME}/.config"
[ ! -L "${HOME}/.config/nvim" ] && ln -s "${HOME}/.vim" "${HOME}/.config/nvim"
