#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sfn "$DIR" "${XDG_CONFIG_HOME}/nvim"

pip install -U -r "${DIR}/requirements.txt"

npm install -g \
  bash-language-server \
  vscode-langservers-extracted \
  neovim

gem install neovim

yarn global add vim-language-server
