#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -sfn "${DIR}" "${XDG_CONFIG_HOME}/nvim"

curl -sfLo "${XDG_CONFIG_HOME}/nvim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim >> /dev/null

mkdir -p "${XDG_DATA_HOME}/nvim/"{backup,swap,undo}
pip3 install -U -r "${DIR}/requirements.txt"

npm install -g \
  bash-language-server \
  ember-template-lint \
  neovim

gem install neovim

yarn global add vim-language-server

nvim +PlugInstall +qall!
