#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pip uninstall -y -r "${DIR}/requirements.txt"
rm -rf "${XDG_CONFIG_HOME}/nvim"
npm uninstall -g \
  ember-template-lint \
  neovim

gem uninstall neovim || true

# rm -rf "$(HOME)/.viminfo"
rm -rf "${HOME}/.vimrc_background"
rm -rf "${DIR}/autoload/plug.vim"
rm -rf "${XDG_DATA_HOME}/nvim/site"
rm -rf "${XDG_CONFIG_HOME}/nvim"
