#!/usr/local/bin/python2
# -*- coding: utf-8 -*-
#
# (C) 2015 Daniel Vrátil &lt;dvratil@kde.org&gt;
# License: GPL
#
 
# https://github.com/gitpython-developers/GitPython
import git
import ConfigParser
import os
import sys
 
repo = git.Repo(os.getcwd())
   
# Don't do anything if an identity is already configured in this
# repo's .git/config
config = repo.config_reader(config_level = 'repository')
try:
    # The value of user.email is non-empty, stop here
    if config.get_value('user', 'email'):
        sys.exit(0)
except (ConfigParser.NoSectionError, ConfigParser.NoOptionError):
    # Section or option does not exist, continue
    pass
               
origin = repo.remote('origin')
if not origin:
    print('** Failed to detect remote origin, identity not updated! **')
    sys.exit(0)
 
# This is where you adjust the code to fit your needs
if 'github.comcast.com' in origin.url:
    email = 'matthew_narrell@comcast.com'
elif 'github.com' in origin.url:
    email = 'mnarrell@gmail.com'
else:
    print('** Failed to detect identity! **')
    sys.exit(0)
         
# Write the option to .git/config
config = repo.config_writer()
config.set_value('user', 'email', email)
config.release()
print('** User identity for this repository set to \'%s\' **' % email)
